config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "home#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logou", to: "sessions#destroy"

  post "/validar-codigo", to: "home#create"
  # get "/formulario", to: "formulario#new"

  resources :formularios, only: [:new, :create]

  namespace :admin do
    resources :codigos, only: [:index, :create] do
      collection do
        get :export_respostas
      end
    end
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController
  def new
    @codigo = params[:codigo]
    @perguntas = Pergunta.todas
  end

  def create
    respostas = respostas_array
    codigo = params[:codigo]

    resposta = Resposta.new(
      codigo: codigo,
      respostas: respostas,
      comentario_final: params[:comentario_final]
    )

    if resposta.save
      Codigo.where(codigo: codigo).first.update(utilizado: true)
      redirect_to root_path, notice: "Pesquisa enviada com sucesso!"
    else
      redirect_to formulario_path(codigo: codigo),
                  alert: resposta.errors.full_messages.first
    end
  end

  def respostas_array
    return [] unless params[:respostas].present?

    params[:respostas]
      .to_unsafe_h
      .sort_by { |k, _| k.to_i }
      .map { |_, v| v.to_i } 
  end
end

app/helpers/formulario_helper.rb
module FormularioHelper
end

app/views/formularios/new.html.erb
<div class="pesquisa-clima">

  <h1>ORIENTAÇÕES GERAIS</h1>
  <p>Olá!</p>

  <p>
    A Pesquisa de Clima Organizacional tem como objetivo compreender a percepção
    dos servidores e colaboradores sobre o ambiente de trabalho.
    Suas respostas são <b>confidenciais e anônimas.</b>
  </p>
  <p>
  Não existem respostas certas ou erradas. O mais importante é que você responda com sinceridade, de acordo com sua experiência no ambiente de trabalho.
</p>

  Em cada item, assinale apenas uma alternativa, conforme a escala abaixo:
  <ul>
    <li>CP – Concordo Plenamente</li>
    <li>IC – Inclinado a Concordar</li>
    <li>ID – Inclinado a Discordar</li>
    <li>DP – Discordo Plenamente</li>
  </ul>

  <%= form_with url: formularios_path, method: :post, local: true,
        data: { turbo: false },
        html: { class: "formulario-clima" } do %>

  <%= hidden_field_tag :codigo, @codigo %>

  <% @perguntas.each do |topico, perguntas| %>
    <h2><%= topico %></h2>
    <% perguntas.each do |numero, texto| %>
      <p><strong><%= "#{numero}. #{texto}" %></strong></p>

      <% {1=>"Concordo Plenamente", 2=>"Inclinado a Concordar", 3=>"Inclinado a Discordar", 4=>"Discordo Plenamente"}.each do |valor,label| %>
        <label>
          <%= radio_button_tag "respostas[#{numero}]", valor, false, required: true %>
          <%= label %>
        </label><br>
      <% end %>
      <hr>
    <% end %>
  <% end %>

  <h3>Comentários finais</h3>
  <p>Utilize o espaço abaixo para registrar comentários, sugestões ou percepções que considere relevantes.
Caso deseje relatar situações relacionadas a desrespeito, assédio moral ou outras condutas inadequadas, utilize este espaço sem necessidade de identificação.</p>

  <%= text_area_tag :comentario_final, nil, maxlength: 250 %>

  <br><br>

  <h4>AS INFORMAÇÕES PRESTADAS NESTA PESQUISA SERÃO TRATADAS COM SIGILO ABSOLUTO.</h4>
  <br><br>
  <%= submit_tag "Enviar", class: "btn btn-success" %>
<% end %>

</div>